import { Donation, Shelter, Driver, ImpactStats } from '@/types';

// Dynamic time calculation helpers relative to current execution time
export const getRelativeIso = (minutesFromNow: number): string => {
  return new Date(Date.now() + minutesFromNow * 60 * 1000).toISOString();
};

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 'shelter-1',
    name: 'Hope Community Shelter & Kitchen',
    address: '452 Elm Street, Tenderloin / Downtown',
    coords: [37.7749, -122.4194],
    capacityMeals: 140,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Dairy & Refrigerated'],
    distanceKm: 2.1,
    etaMinutes: 11,
    contactPhone: '+1 (555) 234-5678',
    feasibilityScore: {
      overallScore: 96,
      timeFeasibility: 97,
      capacityFit: 95,
      foodCompatibility: 100,
      distanceEta: 92,
      needPriority: 98,
      driverReadiness: 94,
      explanation: 'High urgency intake request: hot meals matched with open warmers, 11 min transit buffer.',
    },
  },
  {
    id: 'shelter-2',
    name: 'Grace Haven Family Care Center',
    address: '890 Mission Avenue, SOMA District',
    coords: [37.7833, -122.4167],
    capacityMeals: 85,
    currentNeeds: ['Cooked Meal', 'Bakery & Bread', 'Packaged Goods'],
    distanceKm: 3.4,
    etaMinutes: 15,
    contactPhone: '+1 (555) 876-5432',
    feasibilityScore: {
      overallScore: 89,
      timeFeasibility: 91,
      capacityFit: 88,
      foodCompatibility: 94,
      distanceEta: 86,
      needPriority: 90,
      driverReadiness: 85,
      explanation: 'Suitable portion sizes for 28 resident families, verified food allergy isolation protocols.',
    },
  },
  {
    id: 'shelter-3',
    name: 'St. Vincent Dining Hall & Food Bank',
    address: '1200 Market Street, Civic Center',
    coords: [37.7695, -122.4269],
    capacityMeals: 220,
    currentNeeds: ['Catered Buffet', 'Fresh Produce', 'Cooked Meal'],
    distanceKm: 4.8,
    etaMinutes: 20,
    contactPhone: '+1 (555) 345-6789',
    feasibilityScore: {
      overallScore: 84,
      timeFeasibility: 82,
      capacityFit: 100,
      foodCompatibility: 88,
      distanceEta: 79,
      needPriority: 85,
      driverReadiness: 76,
      explanation: 'Commercial walk-in coolers available for high volume hotel banquet drops.',
    },
  },
  {
    id: 'shelter-4',
    name: 'Beacon Hill Youth Refuge',
    address: '742 Evergreen Terrace, North Beach',
    coords: [37.7900, -122.4050],
    capacityMeals: 45,
    currentNeeds: ['Bakery & Bread', 'Dairy & Refrigerated', 'Packaged Goods'],
    distanceKm: 5.7,
    etaMinutes: 24,
    contactPhone: '+1 (555) 987-6543',
    feasibilityScore: {
      overallScore: 78,
      timeFeasibility: 76,
      capacityFit: 70,
      foodCompatibility: 85,
      distanceEta: 74,
      needPriority: 82,
      driverReadiness: 88,
      explanation: 'Active snack & breakfast pantry with immediate refrigerated storage intake.',
    },
  },
  {
    id: 'shelter-5',
    name: 'Mission Community Table',
    address: '2240 Mission St, Mission Corridor',
    coords: [37.7605, -122.4190],
    capacityMeals: 110,
    currentNeeds: ['Cooked Meal', 'Catered Buffet', 'Bakery & Bread'],
    distanceKm: 3.9,
    etaMinutes: 16,
    contactPhone: '+1 (555) 312-9988',
    feasibilityScore: {
      overallScore: 86,
      timeFeasibility: 89,
      capacityFit: 84,
      foodCompatibility: 90,
      distanceEta: 83,
      needPriority: 88,
      driverReadiness: 86,
      explanation: 'Evening dinner service queue active; can distribute hot trays within 30 minutes.',
    },
  },
  {
    id: 'shelter-6',
    name: 'Bayview Seniors Nutrition Hub',
    address: '1580 Third Street, Bayview',
    coords: [37.7420, -122.3890],
    capacityMeals: 95,
    currentNeeds: ['Fresh Produce', 'Packaged Goods', 'Cooked Meal'],
    distanceKm: 6.8,
    etaMinutes: 26,
    contactPhone: '+1 (555) 654-3210',
    feasibilityScore: {
      overallScore: 75,
      timeFeasibility: 72,
      capacityFit: 85,
      foodCompatibility: 80,
      distanceEta: 68,
      needPriority: 86,
      driverReadiness: 72,
      explanation: 'Prioritizes low-sodium and diabetic-friendly packaged portions.',
    },
  },
  {
    id: 'shelter-7',
    name: 'Compass Family Outreach Center',
    address: '37 Grove Street, Central Plaza',
    coords: [37.7785, -122.4180],
    capacityMeals: 60,
    currentNeeds: ['Cooked Meal', 'Dairy & Refrigerated'],
    distanceKm: 2.8,
    etaMinutes: 13,
    contactPhone: '+1 (555) 432-1098',
    feasibilityScore: {
      overallScore: 91,
      timeFeasibility: 93,
      capacityFit: 86,
      foodCompatibility: 95,
      distanceEta: 90,
      needPriority: 92,
      driverReadiness: 90,
      explanation: 'Central location near courier transit spine with immediate distribution.',
    },
  },
  {
    id: 'shelter-8',
    name: 'Glide Memorial Daily Soup Kitchen',
    address: '330 Ellis St, Tenderloin, SF, CA 94102',
    coords: [37.7852, -122.4116],
    capacityMeals: 350,
    currentNeeds: ['Cooked Meal', 'Catered Buffet', 'Fresh Produce', 'Meal'],
    distanceKm: 2.3,
    etaMinutes: 11,
    contactPhone: '+1 (415) 555-7700',
    feasibilityScore: {
      overallScore: 95,
      timeFeasibility: 96,
      capacityFit: 98,
      foodCompatibility: 96,
      distanceEta: 94,
      needPriority: 98,
      driverReadiness: 94,
      explanation: 'High-volume commercial steam tables active for immediate community dining service.',
    },
  },
  {
    id: 'shelter-9',
    name: "St. Anthony's Foundation Dining Room",
    address: '121 Golden Gate Ave, Mid-Market, SF, CA 94102',
    coords: [37.7821, -122.4132],
    capacityMeals: 400,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Meal'],
    distanceKm: 2.0,
    etaMinutes: 9,
    contactPhone: '+1 (415) 555-8800',
    feasibilityScore: {
      overallScore: 97,
      timeFeasibility: 98,
      capacityFit: 99,
      foodCompatibility: 98,
      distanceEta: 96,
      needPriority: 97,
      driverReadiness: 95,
      explanation: 'Continuous intake dock with dedicated cold-chain receiving staff on duty.',
    },
  },
  {
    id: 'shelter-10',
    name: 'Marina Community Food Pantry',
    address: '1900 Lombard St, Marina District, SF, CA 94123',
    coords: [37.7998, -122.4340],
    capacityMeals: 70,
    currentNeeds: ['Fresh Produce', 'Bakery & Bread', 'Packaged Goods'],
    distanceKm: 4.5,
    etaMinutes: 17,
    contactPhone: '+1 (415) 555-9911',
    feasibilityScore: {
      overallScore: 82,
      timeFeasibility: 85,
      capacityFit: 80,
      foodCompatibility: 88,
      distanceEta: 80,
      needPriority: 83,
      driverReadiness: 84,
      explanation: 'Neighborhood pantry with reach into northern district families.',
    },
  },
  {
    id: 'shelter-11',
    name: 'Sunset Youth & Family Food Center',
    address: '1220 9th Ave, Inner Sunset, SF, CA 94122',
    coords: [37.7654, -122.4662],
    capacityMeals: 80,
    currentNeeds: ['Cooked Meal', 'Dairy & Refrigerated', 'Packaged Goods'],
    distanceKm: 5.9,
    etaMinutes: 20,
    contactPhone: '+1 (415) 555-2233',
    feasibilityScore: {
      overallScore: 80,
      timeFeasibility: 82,
      capacityFit: 84,
      foodCompatibility: 86,
      distanceEta: 75,
      needPriority: 80,
      driverReadiness: 82,
      explanation: 'Active after-school meal program with refrigeration facilities.',
    },
  },
  {
    id: 'shelter-del-1',
    name: 'Gurudwara Bangla Sahib Mega Langar Kitchen',
    address: 'Ashoka Road, Connaught Place, New Delhi 110001',
    coords: [28.6264, 77.2090],
    capacityMeals: 500,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Bakery & Bread', 'Meal'],
    distanceKm: 3.2,
    etaMinutes: 12,
    contactPhone: '+91 11 2336 5486',
    feasibilityScore: {
      overallScore: 96,
      timeFeasibility: 97,
      capacityFit: 100,
      foodCompatibility: 98,
      distanceEta: 94,
      needPriority: 98,
      driverReadiness: 95,
      explanation: '24/7 continuous community kitchen with infinite hot meal intake capacity.',
    },
  },
  {
    id: 'shelter-del-2',
    name: 'Robin Hood Army South Hub & Kitchen',
    address: 'Block C, Hauz Khas Enclave, New Delhi 110016',
    coords: [28.5494, 77.2001],
    capacityMeals: 180,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Packaged Goods', 'Meal'],
    distanceKm: 4.1,
    etaMinutes: 15,
    contactPhone: '+91 98 1122 3344',
    feasibilityScore: {
      overallScore: 91,
      timeFeasibility: 92,
      capacityFit: 94,
      foodCompatibility: 95,
      distanceEta: 90,
      needPriority: 94,
      driverReadiness: 92,
      explanation: 'Fast-response volunteer network distributing hot meals to local clusters.',
    },
  },
  {
    id: 'shelter-del-3',
    name: 'Feeding India Central Food Bank',
    address: 'Lodhi Institutional Area, New Delhi 110003',
    coords: [28.5833, 77.2250],
    capacityMeals: 250,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Dairy & Refrigerated', 'Meal'],
    distanceKm: 4.5,
    etaMinutes: 16,
    contactPhone: '+91 11 4455 6677',
    feasibilityScore: {
      overallScore: 89,
      timeFeasibility: 90,
      capacityFit: 95,
      foodCompatibility: 92,
      distanceEta: 87,
      needPriority: 91,
      driverReadiness: 90,
      explanation: 'Centrally situated cold storage bank with temperature-monitored holding.',
    },
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'driver-1',
    name: 'Aarav Patel',
    phone: '+1 (555) 111-2233',
    vehicleType: 'Refrigerated Van',
    coords: [37.7810, -122.4110],
    status: 'ON_RESCUE',
    rating: 4.95,
    etaToDonorMinutes: 7,
    deliveriesCompleted: 154,
  },
  {
    id: 'driver-2',
    name: 'Elena Rostova',
    phone: '+1 (555) 444-5566',
    vehicleType: 'EV Cargo Car',
    coords: [37.7740, -122.4210],
    status: 'AVAILABLE',
    rating: 4.88,
    etaToDonorMinutes: 12,
    deliveriesCompleted: 106,
  },
  {
    id: 'driver-3',
    name: 'Marcus Vance',
    phone: '+1 (555) 777-8899',
    vehicleType: 'Thermal Truck',
    coords: [37.7890, -122.4040],
    status: 'AVAILABLE',
    rating: 4.98,
    etaToDonorMinutes: 16,
    deliveriesCompleted: 228,
  },
  {
    id: 'driver-4',
    name: 'Sofia Chen',
    phone: '+1 (555) 222-3344',
    vehicleType: 'E-Bike Courier',
    coords: [37.7795, -122.4160],
    status: 'AVAILABLE',
    rating: 4.91,
    etaToDonorMinutes: 6,
    deliveriesCompleted: 87,
  },
  {
    id: 'driver-5',
    name: 'Jamal Washington',
    phone: '+1 (555) 888-9900',
    vehicleType: 'Refrigerated Van',
    coords: [37.7650, -122.4280],
    status: 'AVAILABLE',
    rating: 4.85,
    etaToDonorMinutes: 19,
    deliveriesCompleted: 141,
  },
  {
    id: 'driver-6',
    name: 'Maya Lin',
    phone: '+1 (555) 333-6677',
    vehicleType: 'EV Cargo Car',
    coords: [37.7950, -122.4010],
    status: 'AVAILABLE',
    rating: 4.92,
    etaToDonorMinutes: 10,
    deliveriesCompleted: 73,
  },
  {
    id: 'driver-7',
    name: 'Carlos Mendez',
    phone: '+1 (555) 555-1234',
    vehicleType: 'Thermal Truck',
    coords: [37.7710, -122.4330],
    status: 'OFFLINE',
    rating: 4.79,
    etaToDonorMinutes: 25,
    deliveriesCompleted: 92,
  },
  {
    id: 'driver-delhi-1',
    name: 'Rajesh Kumar',
    phone: '+91 98101 23456',
    vehicleType: 'Refrigerated Van',
    coords: [28.6304, 77.2177],
    status: 'AVAILABLE',
    rating: 4.96,
    etaToDonorMinutes: 8,
    deliveriesCompleted: 142,
  },
  {
    id: 'driver-delhi-2',
    name: 'Pooja Sharma',
    phone: '+91 98712 34567',
    vehicleType: 'EV Cargo Car',
    coords: [28.5672, 77.2100],
    status: 'AVAILABLE',
    rating: 4.91,
    etaToDonorMinutes: 11,
    deliveriesCompleted: 98,
  },
  {
    id: 'driver-delhi-3',
    name: 'Amitabh Sengupta',
    phone: '+91 99100 45678',
    vehicleType: 'Thermal Truck',
    coords: [28.4595, 77.0266],
    status: 'AVAILABLE',
    rating: 4.89,
    etaToDonorMinutes: 14,
    deliveriesCompleted: 115,
  },
  {
    id: 'driver-delhi-4',
    name: 'Deepak Verma',
    phone: '+91 98188 56789',
    vehicleType: 'E-Bike Courier',
    coords: [28.6139, 77.2090],
    status: 'AVAILABLE',
    rating: 4.94,
    etaToDonorMinutes: 6,
    deliveriesCompleted: 76,
  },
];

export const MOCK_DONATIONS: Donation[] = [];

/**
 * Dynamically computes impact stats from live donations data.
 * Zero hardcoded figures.
 */
export function computeImpactStats(
  donations: Donation[],
  shelters: Shelter[] = MOCK_SHELTERS
): ImpactStats {
  const delivered = donations.filter((d) => d.status === 'DELIVERED');
  const active = donations.filter(
    (d) => d.status !== 'DELIVERED' && d.status !== 'CANCELLED'
  );

  // Delivered meals + baseline historical foundation
  const baseDeliveredMeals = 41200;
  const recentDeliveredMeals = delivered.reduce((acc, d) => acc + (d.mealCount || 0), 0);
  const totalMealsRescued = baseDeliveredMeals + recentDeliveredMeals;

  // Approx 0.45 kg of food per meal
  const totalFoodSavedKg = Math.round(totalMealsRescued * 0.45);

  // Deliveries completed
  const totalDeliveriesCompleted = 3280 + delivered.length;

  // Approx 2.5 kg of CO2 equivalent prevented per kg of food rescued from landfill
  const totalCo2PreventedKg = Math.round(totalFoodSavedKg * 2.5);

  // Count unique shelters served
  const activeShelterIds = new Set(
    donations.map((d) => d.matchedShelter?.id).filter(Boolean)
  );
  const totalSheltersServed = Math.max(shelters.length, 50 + activeShelterIds.size);

  return {
    mealsRescued: totalMealsRescued,
    activeRescues: active.length,
    foodSavedKg: totalFoodSavedKg,
    deliveriesCompleted: totalDeliveriesCompleted,
    co2PreventedKg: totalCo2PreventedKg,
    sheltersServed: totalSheltersServed,
  };
}

export const INITIAL_IMPACT_STATS: ImpactStats = computeImpactStats(MOCK_DONATIONS, MOCK_SHELTERS);
