import { Donation, Shelter, Driver, ImpactStats } from '@/types';

export const INITIAL_IMPACT_STATS: ImpactStats = {
  mealsRescued: 42850,
  activeRescues: 18,
  foodSavedKg: 19280,
  deliveriesCompleted: 3410,
  co2PreventedKg: 48200,
  sheltersServed: 64,
};

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 'shelter-1',
    name: 'Hope Community Shelter',
    address: '452 Elm Street, Downtown',
    coords: [37.7749, -122.4194],
    capacityMeals: 120,
    currentNeeds: ['Cooked Meal', 'Fresh Produce', 'Dairy & Refrigerated'],
    distanceKm: 2.4,
    etaMinutes: 12,
    contactPhone: '+1 (555) 234-5678',
    feasibilityScore: {
      overallScore: 94,
      timeFeasibility: 95,
      capacityFit: 92,
      foodCompatibility: 100,
      distanceEta: 90,
      needPriority: 95,
      driverReadiness: 93,
      explanation: 'Hope Shelter has sufficient capacity (120 meals), currently urgently needs hot cooked meals, and is within 12 mins ETA.',
    },
  },
  {
    id: 'shelter-2',
    name: 'Grace Haven Family Care Center',
    address: '890 Mission Ave, District 4',
    coords: [37.7833, -122.4167],
    capacityMeals: 75,
    currentNeeds: ['Cooked Meal', 'Bakery & Bread', 'Packaged Goods'],
    distanceKm: 3.8,
    etaMinutes: 16,
    contactPhone: '+1 (555) 876-5432',
    feasibilityScore: {
      overallScore: 88,
      timeFeasibility: 90,
      capacityFit: 85,
      foodCompatibility: 95,
      distanceEta: 84,
      needPriority: 90,
      driverReadiness: 84,
      explanation: 'Slightly further away but high capacity fit for family portions.',
    },
  },
  {
    id: 'shelter-3',
    name: 'St. Vincent Food Bank & Dining Hall',
    address: '1200 Market Street, Central',
    coords: [37.7695, -122.4269],
    capacityMeals: 200,
    currentNeeds: ['Catered Buffet', 'Fresh Produce'],
    distanceKm: 5.1,
    etaMinutes: 22,
    contactPhone: '+1 (555) 345-6789',
    feasibilityScore: {
      overallScore: 82,
      timeFeasibility: 80,
      capacityFit: 100,
      foodCompatibility: 80,
      distanceEta: 76,
      needPriority: 82,
      driverReadiness: 74,
      explanation: 'Massive capacity available for large catered volume drops.',
    },
  },
  {
    id: 'shelter-4',
    name: 'Beacon Hill Youth Refuge',
    address: '742 Evergreen Terrace, North Side',
    coords: [37.7900, -122.4050],
    capacityMeals: 40,
    currentNeeds: ['Bakery & Bread', 'Dairy & Refrigerated'],
    distanceKm: 6.5,
    etaMinutes: 28,
    contactPhone: '+1 (555) 987-6543',
    feasibilityScore: {
      overallScore: 75,
      timeFeasibility: 72,
      capacityFit: 60,
      foodCompatibility: 75,
      distanceEta: 70,
      needPriority: 80,
      driverReadiness: 90,
      explanation: 'Limited current meal intake capacity, better suited for snack items.',
    },
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'driver-1',
    name: 'Aarav Patel',
    phone: '+1 (555) 111-2233',
    vehicleType: 'Refrigerated Van',
    coords: [37.7780, -122.4150],
    status: 'AVAILABLE',
    rating: 4.9,
    etaToDonorMinutes: 8,
    deliveriesCompleted: 142,
  },
  {
    id: 'driver-2',
    name: 'Elena Rostova',
    phone: '+1 (555) 444-5566',
    vehicleType: 'EV Cargo Car',
    coords: [37.7720, -122.4220],
    status: 'AVAILABLE',
    rating: 4.8,
    etaToDonorMinutes: 14,
    deliveriesCompleted: 98,
  },
  {
    id: 'driver-3',
    name: 'Marcus Vance',
    phone: '+1 (555) 777-8899',
    vehicleType: 'Thermal Truck',
    coords: [37.7850, -122.4100],
    status: 'AVAILABLE',
    rating: 5.0,
    etaToDonorMinutes: 19,
    deliveriesCompleted: 215,
  },
];

// Helper to compute future deadline date string
const getFutureTime = (minutesToAdd: number) => {
  return new Date(Date.now() + minutesToAdd * 60 * 1000).toISOString();
};

export const MOCK_DONATIONS: Donation[] = [
  {
    id: 'RP-1024',
    donorId: 'donor-1',
    donorName: 'Grand Hyatt Hotel Catering',
    donorAddress: '345 Embarcadero Plaza, Financial District',
    donorCoords: [37.7940, -122.3960],
    foodName: 'Paneer Rice & Vegetable Curry Trays',
    category: 'Cooked Meal',
    quantity: '50 packed meals',
    mealCount: 50,
    description: 'Freshly prepared paneer rice and warm vegetable curry in insulated food trays from luncheon conference.',
    prepTime: '7:00 PM',
    availableFrom: '7:30 PM',
    pickupDeadline: getFutureTime(42), // 42 minutes left
    rescueWindowMinutes: 90,
    storageMethod: 'hot_held',
    packagingType: 'sealed',
    allergens: ['Dairy'],
    declarations: {
      safeStorage: true,
      cleanContainers: true,
      noContamination: true,
      donorVerified: true,
    },
    eligibilityStatus: 'ELIGIBLE',
    status: 'PICKUP_IN_PROGRESS',
    matchedShelter: MOCK_SHELTERS[0],
    assignedDriver: MOCK_DRIVERS[0],
    driverCoords: [37.7860, -122.4050],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    urgencyLevel: 'attention',
  },
  {
    id: 'RP-1025',
    donorId: 'donor-2',
    donorName: 'Artisan Bakery & Cafe',
    donorAddress: '512 Valencia St, Mission District',
    donorCoords: [37.7640, -122.4220],
    foodName: 'Artisanal Sourdough & Croissants',
    category: 'Bakery & Bread',
    quantity: '35 loaves / 60 pastries',
    mealCount: 45,
    description: 'Surplus morning artisanal sourdough loaves, whole grain batards, and butter croissants.',
    prepTime: '6:00 AM',
    availableFrom: '8:00 PM',
    pickupDeadline: getFutureTime(110),
    rescueWindowMinutes: 180,
    storageMethod: 'ambient',
    packagingType: 'covered',
    allergens: ['Gluten', 'Butter/Dairy'],
    declarations: {
      safeStorage: true,
      cleanContainers: true,
      noContamination: true,
      donorVerified: true,
    },
    eligibilityStatus: 'ELIGIBLE',
    status: 'MATCHED',
    matchedShelter: MOCK_SHELTERS[1],
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    urgencyLevel: 'normal',
  },
  {
    id: 'RP-1026',
    donorId: 'donor-3',
    donorName: 'Corporate Tech Campus Cafeteria',
    donorAddress: '100 Silicon Way, Soma',
    donorCoords: [37.7810, -122.3990],
    foodName: 'Grilled Chicken & Quinoa Bowls',
    category: 'Cooked Meal',
    quantity: '80 individual containers',
    mealCount: 80,
    description: 'Individually portioned grilled herb chicken with quinoa and roasted vegetables in sealed compostable containers.',
    prepTime: '6:30 PM',
    availableFrom: '7:00 PM',
    pickupDeadline: getFutureTime(18), // Critical! 18 mins left
    rescueWindowMinutes: 60,
    storageMethod: 'refrigerated',
    packagingType: 'individual_containers',
    allergens: [],
    declarations: {
      safeStorage: true,
      cleanContainers: true,
      noContamination: true,
      donorVerified: true,
    },
    eligibilityStatus: 'ELIGIBLE',
    status: 'POSTED',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    urgencyLevel: 'critical',
  },
  {
    id: 'RP-1021',
    donorId: 'donor-1',
    donorName: 'Grand Hyatt Hotel Catering',
    donorAddress: '345 Embarcadero Plaza',
    donorCoords: [37.7940, -122.3960],
    foodName: 'Roasted Mediterranean Salad Trays',
    category: 'Fresh Produce',
    quantity: '30 portions',
    mealCount: 30,
    description: 'Chilled salads with feta cheese, olives, and vinaigrette dressing on the side.',
    prepTime: '12:00 PM',
    availableFrom: '1:00 PM',
    pickupDeadline: getFutureTime(-120),
    rescueWindowMinutes: 120,
    storageMethod: 'refrigerated',
    packagingType: 'sealed',
    allergens: ['Dairy'],
    declarations: {
      safeStorage: true,
      cleanContainers: true,
      noContamination: true,
      donorVerified: true,
    },
    eligibilityStatus: 'ELIGIBLE',
    status: 'DELIVERED',
    matchedShelter: MOCK_SHELTERS[0],
    assignedDriver: MOCK_DRIVERS[1],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    urgencyLevel: 'normal',
  }
];
